/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FieldsPane: typeof import('./src/components/FieldsPane.vue')['default']
    LayoutPane: typeof import('./src/components/LayoutPane.vue')['default']
    PreviewPane: typeof import('./src/components/PreviewPane.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPane: typeof import('./src/components/SettingsPane.vue')['default']
  }
}
